### ISSUE TITLE
A probably bug in downloading the history scrape CSV file

### ISSUE THREAD

**Issue by feixiangdejiahao** [ebmdatalab/fdaaa_requirements#1]
The [update_Final FDAAA Issues Notebook_2021.ipynb](https://github.com/ebmdatalab/fdaaa_requirements/blob/master/notebooks/update_Final%20FDAAA%20Issues%20Notebook_2021.ipynb) for this repo has a section to download the history_scrape_yyyy-mm-dd.csv. 
```python
try: 
    docs_updates = pd.read_csv(parent + '/data/history_scrape_2021-01-18.csv')
except FileNotFoundError:
    from lib.trial_history import history_scrape
    most_recent_doc_update = history_scrape(tqdm(has_docs_ids[820:]), date(2021,1,18))
    docs_updates = pd.DataFrame(most_recent_doc_update)
    docs_updates.to_csv('history_scrape_{}.csv'.format(date(2021,1,18)))
```
It seems impossible to retrieve the original csv file ([history_scrape_2021-01-18.csv](https://github.com/ebmdatalab/fdaaa_requirements/blob/master/data/history_scrape_2021-01-18.csv)) by executing the code in `except FileNotFoundError`. The problem may be caused by the constant '820' in the following code. 
```python
most_recent_doc_update = history_scrape(tqdm(has_docs_ids[820:]), date(2021,1,18))
```
I tried to modify the code to use all nct_id and get the correct result.
```python
most_recent_doc_update = history_scrape(tqdm(has_docs_ids[:]), date(2021,1,18))
```

**Comment by NickCEBM** [comment]
Thanks for this (sorry it took me a bit to notice!). I've fixed this in the code. Was leftover from running it and having a break in the data when the scrape was running and obviously I carried over the live fix into the main code! Glad you could reproduce with the fix. @feixiangdejiahao
